### ISSUE TITLE
Invalid Permissions

### ISSUE THREAD

**Issue by DanyPalma** [cfrankovich/ChestLogger#3]
Users have no access to commands inside of the plugin

In `https://github.com/cfrankovich/ChestLogger/blob/main/src/dev/frankovich/main/commands/ChestCommand.java`

Remove Lines 40-44 to allow all users to add chests and access ledgers
```
if (!p.hasPermission("chest.use"))
		{
			sender.sendMessage("§c[ChestLogger] You do not have permission to execute this command.");
			return true;
		}
```
see "Target Selectors" for further information about user groups
> https://minecraft.fandom.com/wiki/Target_selectors

**Comment by cfrankovich** [comment]
Fixed in commit [`c9afdeb`](https://github.com/cfrankovich/ChestLogger/commit/c9afdeb93587156da8b96dbde037dc2102b2b897)
